//QUEUE CONTROLS
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';
export const SET_QUEUE = 'SET_QUEUE';

//PLAYBACK CONTROL
export const SET_PLAYING = 'SET_PLAYING';
export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const NEXT_SONG = 'NEXT_SONG';
export const PREVIOUS_SONG = 'PREVIOUS_SONG';
export const SEEK_TO = 'SEEK_TO';
export const SET_DURATION = 'SET_DURATION';
export const UPDATE_TIME = 'UPDATE_TIME';
export const END_PLAYBACK = 'END_PLAYBACK';

//VIEW CONTROL
export const CHANGE_ACTIVE_CATEGORY = 'CHANGE_ACTIVE_CATEGORY';
export const CHANGE_VISIBLE_CATEGORY = 'CHANGE_VISIBLE_CATEGORY';
export const CHANGE_ACTIVE_INDEX = 'CHANGE_ACTIVE_INDEX';

//NOWPLAYING BAR SETTINGS
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const TOGGLE_LOOP = 'TOGGLE_LOOP';
export const TOGGLE_QUEUE = 'TOGGLE_QUEUE';
export const TOGGLE_VOLUME = 'TOGGLE_VOLUME';
export const CHANGE_VOLUME = 'CHANGE_VOLUME';

//DATA CONTROL
export const UPDATE_DATA = 'UPDATE_DATA';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const REMOVE_PLAYLIST = 'REMOVE_PLAYLIST';
export const RENAME_PLAYLIST = 'RENAME_PLAYLIST';


//PLAYLIST CONTROL
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const REMOVE_FROM_PLAYLIST = 'REMOVE_FROM_PLAYLIST';